---
- hosts: master
  tasks:
    - name: Download GPG key
      shell: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
    - name: Apt transport HTTPS
      become: yes
      apt:
        name: apt-transport-https
        update_cache: yes
    - name: Save repository definition
      shell: echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list
      become: yes
    - name: Install ElasticSearch and Kibana
      become: yes
      apt:
        name:
          - elasticsearch
          - kibana
        update_cache: yes
    - name: Copy kibana.yml file (Kibana config) to allow remote connexions
      become: yes
      copy:
        src: files/kibana.yml
        dest: /etc/kibana/kibana.yml
    - name: Enable ElasticSearch daemon
      become: yes
      systemd:
        enabled: yes
        name: elasticsearch
        state: started
    - name: Enable Kibana daemon
      become: yes
      systemd:
        enabled: yes
        name: kibana
        state: started
