---
- hosts: all
  tasks:
    - name: Download metricbeat
      get_url:
        dest: .
        url: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.8.0-amd64.deb
    - name: Install metricbeat
      become: yes
      command: dpkg -i metricbeat-7.8.0-amd64.deb
    - name: Copy configuration file
      become: yes
      copy:
        src: files/metricbeat.yml
        dest: /etc/metricbeat/metricbeat.yml
    - name: Enable system module
      become: yes
      command: metricbeat modules enable system
    - name: Start metricbeat p1
      become: yes
      command: metricbeat setup
    - name: Start metricbeat p2
      become: yes
      command: service metricbeat start
